# Generated by Django 5.0.2 on 2024-02-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0010_rename_nom_commentaire_namuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
