# Generated by Django 5.0.2 on 2024-02-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0012_alter_evenement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
