# Generated by Django 5.0.2 on 2024-02-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBFinance', '0013_alter_commentaire_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
